package main

import "fmt"

// http://projecteuler.net/problem=
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var answer int

func Fib(previous, current, mod int) {

	total := previous + current

	if current >= 4000000 {
		return
	}

	// ignore odd numbers
	// answer involves every 3rd number after 2.
	if mod%3 != 0 {
		mod += 1
		Fib(current, total, mod)
		return
	}

	fmt.Printf("%d\n", total)
	answer += total
	Fib(current, total, 1)
}

func main() {
	answer = 2
	Fib(1, 2, 1)

	fmt.Printf("answer %d\n", answer)
}
